import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  { ignores: ["dist"] },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": [
        "warn",
        { allowConstantExport: true },
      ],
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  {
    /**
     * previewAuthStorage.ts is regenerated by the Lovable editor, which has now
     * reverted the same prefer-const fix three times (once stripping only the
     * explaining comment, once the eslint-disable with it, and once rewriting
     * the const back to a let). `timer` is assigned exactly once but is cleared
     * by a closure declared above it, so prefer-const cannot see the ordering
     * constraint and the code is correct as generated.
     *
     * Scoping the rule off for this one generated file keeps the lint run at
     * zero errors without fighting the generator on every sync.
     */
    files: ["src/integrations/supabase/previewAuthStorage.ts"],
    rules: {
      "prefer-const": "off",
    },
  }
);
