// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aexuhtpseiryxqxwbthw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFleHVodHBzZWlyeXhxeHdidGh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MDE2NjUsImV4cCI6MjA2OTI3NzY2NX0.Rw_vEReelS0aGnURBRsaFwZmHbBmKJz-gT7Pyj5R3q8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});