// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjsbzhcbcsylmfkdcxeo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqc2J6aGNiY3N5bG1ma2RjeGVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMzMjI3MzQsImV4cCI6MjA4ODg5ODczNH0.aJn5q_CCJG2xwFOKP5FiOuKXYuVf3IDKzCEveTdMhKU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});